name: Build Project

on:
  push:
  workflow_dispatch: 
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build
        run: echo "Building project..."
name: Build Two Projects

on: push

jobs:
  build-project-a:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Build Project A
        run: dotnet build ProjectA/ProjectA.csproj --configuration Release


  build-project-b:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Build Project B
        run: dotnet build ProjectB/ProjectB.csproj --configuration Release
